window.LOOP_VIDEOS = [
  {
    id: 'space-facts-01',
    topic: 'Ciencia',
    title: '5 incredible facts about space',
    channel: 'Educational Shorts',
    duration: 'PT34S',
    publishedAt: '2021-06-13T17:00:34Z',
    url: 'https://www.youtube.com/watch?v=p_XFXSlsUQs',
    video_id: 'p_XFXSlsUQs',
    views: '4065608',
    quality: 82,
    usefulness: 76,
    summary: 'Cápsula rápida para despertar curiosidad sobre astronomía y escala del universo.',
    reason: 'Alta retención potencial, duración corta y tema de entrada fácil para usuarios nuevos.'
  },
  {
    id: 'language-01',
    topic: 'Idiomas',
    title: 'Three English expressions you can use today',
    channel: 'Language Microtips',
    duration: 'PT42S',
    publishedAt: '2022-02-02T10:00:00Z',
    url: 'https://www.youtube.com/watch?v=HAnw168huqA',
    video_id: 'HAnw168huqA',
    views: '875000',
    quality: 78,
    usefulness: 88,
    summary: 'Microlección práctica con expresiones de uso diario.',
    reason: 'Contenido accionable, fácil de repetir y útil para aprendizaje pasivo.'
  },
  {
    id: 'psychology-01',
    topic: 'Psicología',
    title: 'Why habits are hard to break',
    channel: 'Mind Lab',
    duration: 'PT51S',
    publishedAt: '2020-11-12T09:30:00Z',
    url: 'https://www.youtube.com/watch?v=OMbsGBlpP30',
    video_id: 'OMbsGBlpP30',
    views: '1250000',
    quality: 84,
    usefulness: 81,
    summary: 'Explicación breve sobre señales, recompensa y repetición.',
    reason: 'Conecta directamente con la propuesta de LOOP: transformar hábitos de scroll.'
  },
  {
    id: 'technology-01',
    topic: 'Tecnología',
    title: 'What is an API in 45 seconds?',
    channel: 'Tech Basics',
    duration: 'PT45S',
    publishedAt: '2021-09-24T14:00:00Z',
    url: 'https://www.youtube.com/watch?v=s7wmiS2mSXY',
    video_id: 's7wmiS2mSXY',
    views: '642000',
    quality: 80,
    usefulness: 85,
    summary: 'Introducción visual y simple al concepto de API.',
    reason: 'Buen equilibrio entre concepto técnico y explicación accesible.'
  },
  {
    id: 'gardening-01',
    topic: 'Jardinería',
    title: 'How to water plants without overwatering',
    channel: 'Plant Minute',
    duration: 'PT39S',
    publishedAt: '2023-04-10T08:00:00Z',
    url: 'https://www.youtube.com/watch?v=5I4h8D_R1wY',
    video_id: '5I4h8D_R1wY',
    views: '312000',
    quality: 72,
    usefulness: 89,
    summary: 'Consejo práctico para cuidar plantas de interior.',
    reason: 'Tema cotidiano, muy aplicable y adecuado para formato de microaprendizaje.'
  },
  {
    id: 'history-01',
    topic: 'Historia',
    title: 'A tiny history of the Roman roads',
    channel: 'History Bites',
    duration: 'PT56S',
    publishedAt: '2019-07-19T12:00:00Z',
    url: 'https://www.youtube.com/watch?v=Yu94s66Eas8',
    video_id: 'Yu94s66Eas8',
    views: '980000',
    quality: 79,
    usefulness: 70,
    summary: 'Contexto histórico en formato muy breve.',
    reason: 'Sirve para probar variedad temática y retención basada en curiosidad.'
  }
];
